### PR TITLE
Issue 4: configure prettier - script and pre-commit hook

### LINKED ISSUE #4: Configure ESLint and Prettier
- Set up basic configs for ESLint and Prettier
- Reference: https://www.youtube.com/watch?v=11jpa8e5jEQ

### PR DESCRIPTION
**Pull request by koo-mi**
`npm run format` will run Prettier to format the code.
`npm run lint` will run ESLint to lint the code. 

When making commits, prettier will automatically run to format the code. 
- Done by husky and lint-staged

**Prettier Setting**
- use tab (4 spaces) for indentation 
- add semi-colon
- change quote to what is mostly used 
- remove unnecessary trailing commas

### CODE REVIEW

**Comment by tonywucs** [comment]
Great work! Prettier and Linting works so far. There are a few warning that pop up after linting though for img tags, might be good to fix that.

**Comment by tonywucs** [comment]
Seems like when I run this on my local environment it makes changes to all the files as well. Will need to figure this out in the next meeting.

**Comment by koo-mi** [comment]
I think it's supposed to make changes to all files if they don't match with prettier format. 
Let's discuss it tomorrow when we meet up.

**Comment by tonywucs** [comment]
Set default eol settings in vscode to LF and warnings are fixed. Looks good to merge.

**Pull request merged**
